### ISSUE TITLE
Want to Add Java Algorithms 

### ISSUE THREAD

**Issue by Adidem23** [arjunpndt/Hacktoberfest#15]
I have Some Java Related Alogorithms in the Code Folder

**Comment by arjunpndt** [comment]
java algorithm? the code folder is waiting!

**Comment by Adidem23** [comment]
Means algorithms related ai and other problems in Java like 
- BFS DFS
- Tic tac toe game with ai and non ai approach
- greedy algorithms
- constraint satisfication problems like this . By mistake I have algorithms in Java 😂

**Comment by arjunpndt** [comment]
Absolutely! Your java algorithms will greatly enhance the repo's quality. please go ahead!!
